apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HTTPRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/standard-install.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: HTTPRepository
    name: gateway-api
  path: "./"
  targetNamespace: gateway-system
