apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo-ing
  namespace: podinfo2
spec:
  ingressClassName: nginx
  rules:
  - host: podinfo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-podinfo
            port:
              number: 9898
