apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - flux-system/
  - 07-users-rolebindings/
  - 10-prometheus/
  - 15-crossplane/
  - 25-nginx-gateway/
  - 50-dashboard/
  - 55-podinfo2/
